vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'junegunn/vim-easy-align'
  use 'tpope/vim-sensible'
  use 'dpelle/vim-LanguageTool'
  use 'frazrepo/vim-rainbow'
  use 'preservim/nerdtree'
  use 'ryanoasis/vim-devicons'
  use 'tc50cal/vim-terminal'
  use 'scrooloose/syntastic'
  use 'Yggdroot/indentLine'
  use 'navarasu/onedark.nvim'
  use 'rafi/awesome-vim-colorschemes'
  use 'chrisbra/csv.vim'
  use 'lervag/vimtex'
  use 'othree/xml.vim'
  use 'github/copilot.vim'
  use 'preservim/tagbar'
  use 'glepnir/dashboard-nvim' 
  use 'junegunn/fzf.vim'
  use 'tpope/vim-commentary'
  -- use 'neoclide/coc.nvim'
  use 'vim-airline/vim-airline'
  use 'vim-airline/vim-airline-themes'
  use 'dkarter/bullets.vim'
  use 'terryma/vim-multiple-cursors'
end)
